# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import SimuDrones_pb2 as SimuDrones__pb2


class GetPlanStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPos = channel.unary_unary(
                '/GetPlan/GetPos',
                request_serializer=SimuDrones__pb2.PlanRequest.SerializeToString,
                response_deserializer=SimuDrones__pb2.PlanReply.FromString,
                )
        self.GetPack = channel.unary_unary(
                '/GetPlan/GetPack',
                request_serializer=SimuDrones__pb2.NumPackRequest.SerializeToString,
                response_deserializer=SimuDrones__pb2.PackReply.FromString,
                )


class GetPlanServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPack(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GetPlanServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPos': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPos,
                    request_deserializer=SimuDrones__pb2.PlanRequest.FromString,
                    response_serializer=SimuDrones__pb2.PlanReply.SerializeToString,
            ),
            'GetPack': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPack,
                    request_deserializer=SimuDrones__pb2.NumPackRequest.FromString,
                    response_serializer=SimuDrones__pb2.PackReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GetPlan', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GetPlan(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GetPlan/GetPos',
            SimuDrones__pb2.PlanRequest.SerializeToString,
            SimuDrones__pb2.PlanReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetPack(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GetPlan/GetPack',
            SimuDrones__pb2.NumPackRequest.SerializeToString,
            SimuDrones__pb2.PackReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
